package di.uniba.map.b.adventure.gui;

import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author Leonardo Montemurro, Lorenzo Saracino, Vincenzo Sarra
 */
public class Keypad extends JDialog {

  /**
   * Oggetto StringBuilder utilizzato per memorizzare una password inserita.
   */
  StringBuilder enteredPassword = new StringBuilder("");

  /**
   * Restituisce il testo memorizzato nell'oggetto StringBuilder.
   *
   * @return Oggetto StringBuilder contenente il testo memorizzato.
   */
  public StringBuilder getText() {
    return new StringBuilder(enteredPassword);
  }

  /**
   * Costruttore pubblico di KeyPad
   */
  public Keypad() {
    super((JFrame) null, true);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    KeySix = new javax.swing.JButton();
    KeySeven = new javax.swing.JButton();
    KeyEight = new javax.swing.JButton();
    KeyNine = new javax.swing.JButton();
    KeyZero = new javax.swing.JButton();
    EnterKey = new javax.swing.JButton();
    KeyOne = new javax.swing.JButton();
    display = new javax.swing.JLabel();
    KeyTwo = new javax.swing.JButton();
    cancButton = new javax.swing.JButton();
    KeyThree = new javax.swing.JButton();
    KeyFour = new javax.swing.JButton();
    KeyFive = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Tastierino Numerico");
    setAlwaysOnTop(true);
    setResizable(false);

    KeySix.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
    KeySix.setText("6");
    KeySix.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        KeySixActionPerformed(evt);
      }
    });

    KeySeven.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
    KeySeven.setText("7");
    KeySeven.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        KeySevenActionPerformed(evt);
      }
    });

    KeyEight.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
    KeyEight.setText("8");
    KeyEight.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        KeyEightActionPerformed(evt);
      }
    });

    KeyNine.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
    KeyNine.setText("9");
    KeyNine.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        KeyNineActionPerformed(evt);
      }
    });

    KeyZero.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
    KeyZero.setText("0");
    KeyZero.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        KeyZeroActionPerformed(evt);
      }
    });

    EnterKey.setIcon(new javax.swing.ImageIcon("./resources/images/KeyPad/enterkey.png"));
    EnterKey.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        EnterKeyActionPerformed(evt);
      }
    });

    KeyOne.setFont(new java.awt.Font("Hack", 1, 16)); // NOI18N
    KeyOne.setText("1");
    KeyOne.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        KeyOneActionPerformed(evt);
      }
    });

    display.setFont(new java.awt.Font("Hack", 0, 48)); // NOI18N
    display.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    display.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

    KeyTwo.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
    KeyTwo.setText("2");
    KeyTwo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        KeyTwoActionPerformed(evt);
      }
    });

    cancButton.setText("CANC");
    cancButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancButtonActionPerformed(evt);
      }
    });

    KeyThree.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
    KeyThree.setText("3");
    KeyThree.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        KeyThreeActionPerformed(evt);
      }
    });

    KeyFour.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
    KeyFour.setText("4");
    KeyFour.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        KeyFourActionPerformed(evt);
      }
    });

    KeyFive.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
    KeyFive.setText("5");
    KeyFive.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        KeyFiveActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addGap(0, 21, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                            .addGap(30, 30, 30)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(KeyOne, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(40, 40, 40)
                                                            .addComponent(KeyTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(30, 30, 30)
                                                            .addComponent(KeyThree, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(KeyFour, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(40, 40, 40)
                                                            .addComponent(KeyFive, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(30, 30, 30)
                                                            .addComponent(KeySix, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(KeySeven, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(40, 40, 40)
                                                            .addComponent(KeyEight, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(30, 30, 30)
                                                            .addComponent(KeyNine, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addComponent(cancButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(40, 40, 40)
                                                            .addComponent(KeyZero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(30, 30, 30)
                                                            .addComponent(EnterKey, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGap(0, 20, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(KeyOne, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(KeyTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(KeyThree, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(KeyFour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(KeyFive, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(KeySix, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(KeySeven, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(KeyEight, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(KeyNine, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cancButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(KeyZero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EnterKey, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
    setLocationRelativeTo(null);
  } // </editor-fold>//GEN-END:initComponents

  /**
   * Gestisce l'azione quando viene premuto il tasto "6".
   *
   * @param evt L'evento dell'azione generato dal tasto "6".
   */
  private void KeySixActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_KeySixActionPerformed

    Music.playEffect("./resources/soundEffects/click.wav");
    enteredPassword.append("6");
    display.setText(enteredPassword.toString());

  } //GEN-LAST:event_KeySixActionPerformed

  /**
   * Gestisce l'azione quando viene premuto il tasto "7".
   *
   * @param evt L'evento dell'azione generato dal tasto "7".
   */
  private void KeySevenActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_KeySevenActionPerformed

    Music.playEffect("./resources/soundEffects/click.wav");
    enteredPassword.append("7");
    display.setText(enteredPassword.toString());
  } //GEN-LAST:event_KeySevenActionPerformed

  /**
   * Gestisce l'azione quando viene premuto il tasto "8".
   *
   * @param evt L'evento dell'azione generato dal tasto "8".
   */
  private void KeyEightActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_KeyEightActionPerformed

    Music.playEffect("./resources/soundEffects/click.wav");
    enteredPassword.append("8");
    display.setText(enteredPassword.toString());
  } //GEN-LAST:event_KeyEightActionPerformed

  /**
   * Gestisce l'azione quando viene premuto il tasto "9".
   *
   * @param evt L'evento dell'azione generato dal tasto "9".
   */
  private void KeyNineActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_KeyNineActionPerformed

    Music.playEffect("./resources/soundEffects/click.wav");
    enteredPassword.append("9");
    display.setText(enteredPassword.toString());
  } //GEN-LAST:event_KeyNineActionPerformed

  /**
   * Gestisce l'azione quando viene premuto il tasto "0".
   *
   * @param evt L'evento dell'azione generato dal tasto "0".
   */
  private void KeyZeroActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_KeyZeroActionPerformed

    Music.playEffect("./resources/soundEffects/click.wav");
    enteredPassword.append("0");
    display.setText(enteredPassword.toString());
  }//GEN-LAST:event_KeyZeroActionPerformed

  /**
   * Gestisce l'azione quando viene premuto il tasto "enter".
   *
   * @param evt L'evento dell'azione generato dal tasto "enter".
   */
  private void EnterKeyActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_EnterKeyActionPerformed

    if (enteredPassword.toString().equals(enteredPassword.toString())){


      this.dispose();
    }
  } //GEN-LAST:event_EnterKeyActionPerformed

  /**
   * Gestisce l'azione quando viene premuto il tasto "1".
   *
   * @param evt L'evento dell'azione generato dal tasto "1".
   */
  private void KeyOneActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_KeyOneActionPerformed
    Music.playEffect("./resources/soundEffects/click.wav");
    enteredPassword.append("1");
    display.setText(enteredPassword.toString());
  } //GEN-LAST:event_KeyOneActionPerformed

  /**
   * Gestisce l'azione quando viene premuto il tasto "2".
   *
   * @param evt L'evento dell'azione generato dal tasto "2".
   */
  private void KeyTwoActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_KeyTwoActionPerformed
    Music.playEffect("./resources/soundEffects/click.wav");
    enteredPassword.append("2");
    display.setText(enteredPassword.toString());
  } //GEN-LAST:event_KeyTwoActionPerformed

  /**
   * Gestisce l'azione quando viene premuto il tasto "canc".
   *
   * @param evt L'evento dell'azione generato dal tasto "canc".
   */
  private void cancButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancButtonActionPerformed
    display.setText(null);
    enteredPassword.delete(0, enteredPassword.length());
    display.setText(null);
  } //GEN-LAST:event_cancButtonActionPerformed

  /**
   * Gestisce l'azione quando viene premuto il tasto "3".
   *
   * @param evt L'evento dell'azione generato dal tasto "3".
   */
  private void KeyThreeActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_KeyThreeActionPerformed
    Music.playEffect("./resources/soundEffects/click.wav");
    enteredPassword.append("3");
    display.setText(enteredPassword.toString());
  } //GEN-LAST:event_KeyThreeActionPerformed

  /**
   * Gestisce l'azione quando viene premuto il tasto "4".
   *
   * @param evt L'evento dell'azione generato dal tasto "4".
   */
  private void KeyFourActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_KeyFourActionPerformed
    Music.playEffect("./resources/soundEffects/click.wav");
    enteredPassword.append("4");
    display.setText(enteredPassword.toString());
  } //GEN-LAST:event_KeyFourActionPerformed

  /**
   * Gestisce l'azione quando viene premuto il tasto "5".
   *
   * @param evt L'evento dell'azione generato dal tasto "5".
   */
  private void KeyFiveActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_KeyFiveActionPerformed
    Music.playEffect("./resources/soundEffects/click.wav");
    enteredPassword.append("5");
    display.setText(enteredPassword.toString());
  } //GEN-LAST:event_KeyFiveActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private static javax.swing.JButton EnterKey;
  private static javax.swing.JButton KeyEight;
  private static javax.swing.JButton KeyFive;
  private static javax.swing.JButton KeyFour;
  private static javax.swing.JButton KeyNine;
  private static javax.swing.JButton KeyOne;
  private static javax.swing.JButton KeySeven;
  private static javax.swing.JButton KeySix;
  private static javax.swing.JButton KeyThree;
  private static javax.swing.JButton KeyTwo;
  private static javax.swing.JButton KeyZero;
  private static javax.swing.JButton cancButton;
  private static javax.swing.JLabel display;
  // End of variables declaration//GEN-END:variables

}
